version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ssm-slackbot"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15fefioznww8l"
s3_prefix = "ssm-slackbot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SlackWebhookUrlParam=\"/slack-bot-ssm/SlackWebhookURL\" LoggingLevel=\"DEBUG\""
